theme: jekyll-theme-minimal
title: Gavin Morgan, Software
description: ğŸ’» Full-stack software developer, with a side-hat for ğŸ© UX testing, ğŸ© customer development, and ğŸ© lean/xp/agile facilitation.
google_analytics: G-SBQWZTDYBV
